spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/horse_schema?createDatabaseIfNotExist=true
    username: postgres
    password: horseroot
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL #new
    show-sql: true

    hibernate:
      ddl-auto: 'update'

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
